name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name newbee1905
          git config --global user.email beenewminh@outlook.com
          npm install
          npm run build
          git commit -am "Automated build"
          git push
